In [18]:
import pandas as pd
import numpy as np

In [25]:
data = pd.read_csv("../Data/laptop_EDA4.csv")

In [26]:
df = pd.DataFrame()

In [27]:
data.head()

,Ekran_Boyutu,Ekran_Karti,Ekran_Yenileme_Hizi,Hard_Disk_Kapasitesi,Ram,SSD_Kapasitesi,Cozunurluk,Islemci_Nesli,Islemci_Tipi,Isletim_Sistemi,url,price,marka
0,15.6,Dahili Ekran Kartı,60.0,0.0,4.0,0.0,1366 x 768,4.0,Intel Celeron,Free Dos,https://www.trendyol.com//lenovo/ideapad1-inte...,6.7990,lenovo
1,13.0,M1 7 Çekirdekli,60.0,256.0,16.0,256.0,2560 x 1600,13.0,Apple M1,Mac Os,https://www.trendyol.com//monster/abra-a5-v16-...,22.9733,monster
2,15.6,AMD Radeon Graphics,60.0,0.0,16.0,512.0,1920 x 1080,5.0,AMD Ryzen 7,Free Dos,https://www.trendyol.com//lenovo/ideapad-amd-r...,13.0990,lenovo
3,15.6,Nvidia GeForce RTX 2050,144.0,0.0,8.0,512.0,1920 x 1080,11.0,Intel Core i5,Free Dos,https://www.trendyol.com//asus/tuf-gaming-f15-...,24.7500,asus
4,15.6,Intel UHD Graphics,60.0,0.0,4.0,128.0,1920 x 1080,2.0,Intel Celeron,Linux,https://www.trendyol.com//acer/aspire3-intel-c...,6.2900,acer

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1776 entries, 0 to 1775
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Ekran_Boyutu          1751 non-null   float64
 1   Ekran_Karti           1743 non-null   object
 2   Ekran_Yenileme_Hizi   1727 non-null   float64
 3   Hard_Disk_Kapasitesi  1736 non-null   float64
 4   Ram                   1743 non-null   float64
 5   SSD_Kapasitesi        1751 non-null   float64
 6   Cozunurluk            1743 non-null   object
 7   Islemci_Nesli         1736 non-null   float64
 8   Islemci_Tipi          1743 non-null   object
 9   Isletim_Sistemi       1743 non-null   object
 10  url                   1776 non-null   object
 11  price                 1776 non-null   float64
 12  marka                 1776 non-null   object
dtypes: float64(7), object(6)
memory usage: 180.5+ KB

In [29]:
df['marka'] = data['marka']
df['Isletim_Sistemi'] = data['Isletim_Sistemi']
df['Islemci_Tipi'] = data['Islemci_Tipi']
df['Islemci_Nesli'] = data['Islemci_Nesli']
df['Cozunurluk'] = data['Cozunurluk']
df['SSD_Kapasitesi'] = data['SSD_Kapasitesi']
df['Ram'] = data['Ram']
df['Hard_Disk_Kapasitesi'] = data['Hard_Disk_Kapasitesi']
df['Ekran_Yenileme_Hizi'] = data['Ekran_Yenileme_Hizi']
df['Ekran_Karti'] = data['Ekran_Karti']
df['Ekran_Boyutu'] = data['Ekran_Boyutu']
df['Fiyat'] = data['price']

In [30]:
df.head()

,marka,Isletim_Sistemi,Islemci_Tipi,Islemci_Nesli,Cozunurluk,SSD_Kapasitesi,Ram,Hard_Disk_Kapasitesi,Ekran_Yenileme_Hizi,Ekran_Karti,Ekran_Boyutu,Fiyat
0,lenovo,Free Dos,Intel Celeron,4.0,1366 x 768,0.0,4.0,0.0,60.0,Dahili Ekran Kartı,15.6,6.7990
1,monster,Mac Os,Apple M1,13.0,2560 x 1600,256.0,16.0,256.0,60.0,M1 7 Çekirdekli,13.0,22.9733
2,lenovo,Free Dos,AMD Ryzen 7,5.0,1920 x 1080,512.0,16.0,0.0,60.0,AMD Radeon Graphics,15.6,13.0990
3,asus,Free Dos,Intel Core i5,11.0,1920 x 1080,512.0,8.0,0.0,144.0,Nvidia GeForce RTX 2050,15.6,24.7500
4,acer,Linux,Intel Celeron,2.0,1920 x 1080,128.0,4.0,0.0,60.0,Intel UHD Graphics,15.6,6.2900

In [31]:
df.to_csv("../data/laptop-to-presentation.csv",index=False)

In [32]:
df['marka'].value_counts()

lenovo            371
asus              358
dell              325
hp                229
acer              127
casper             90
msi                71
apple              63
monster            61
everest            23
huawei             21
toshiba             8
microsoft           5
gigabyte            4
hometech            3
samsung             3
technopc            3
honor               3
i-life-digital      1
fosiltech           1
hpe                 1
xiaomi              1
ilife               1
dts-teknoloji       1
tecno               1
von-januar          1
Name: marka, dtype: int64

In [33]:
df['Islemci_Tipi'].value_counts()

Intel Core i5              763
Intel Core i7              278
AMD Ryzen 5                116
AMD Ryzen 7                116
Intel Core i3              114
Intel Celeron               76
Apple M1                    67
Intel Core i9               58
AMD Ryzen 3                 42
M2                          22
Apple M2                    13
Intel Xeon                  11
MediaTek P60T               10
AMD Ryzen 9                  8
AMD                          7
AMD Athlon                   6
Apple M1 Pro                 5
Intel Pentium                5
Intel Core M                 4
M3                           4
Intel Atom                   3
Apple M2 Pro                 2
AMD E                        2
AMD A6                       2
AMD A4                       2
Ryzen Z1                     1
AMD A9                       1
Ryzen Z1 Extreme             1
Apple M1 Max                 1
Apple M2 Max                 1
Intel Xeon W Serisi          1
Intel Pentium Dual Core      1
Name: Islemci_Tipi, dtype: int64

In [35]:
df['Isletim_Sistemi'].value_counts()

Free Dos      905
Windows       688
Mac Os        114
Linux          20
Windows 11      6
Ubuntu          6
Chrome OS       4
Name: Isletim_Sistemi, dtype: int64

In [36]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

In [37]:
df['marka'] = enc.fit_transform(df['marka'])

In [39]:
df['marka'].value_counts()

16    371
2     358
4     325
11    229
0     127
3      90
19     71
1      63
18     61
6      23
13     21
23      8
17      5
8       4
9       3
20      3
21      3
10      3
14      1
7       1
12      1
25      1
15      1
5       1
22      1
24      1
Name: marka, dtype: int64

In [40]:
df['Isletim_Sistemi'].value_counts()

Free Dos      905
Windows       688
Mac Os        114
Linux          20
Windows 11      6
Ubuntu          6
Chrome OS       4
Name: Isletim_Sistemi, dtype: int64

In [41]:
df['Isletim_Sistemi'] = enc.fit_transform(df['Isletim_Sistemi'])

In [42]:
df['Isletim_Sistemi'].value_counts()

1    905
5    688
3    114
7     33
2     20
6      6
4      6
0      4
Name: Isletim_Sistemi, dtype: int64

In [43]:
df.head()

,marka,Isletim_Sistemi,Islemci_Tipi,Islemci_Nesli,Cozunurluk,SSD_Kapasitesi,Ram,Hard_Disk_Kapasitesi,Ekran_Yenileme_Hizi,Ekran_Karti,Ekran_Boyutu,Fiyat
0,16,1,Intel Celeron,4.0,1366 x 768,0.0,4.0,0.0,60.0,Dahili Ekran Kartı,15.6,6.7990
1,18,3,Apple M1,13.0,2560 x 1600,256.0,16.0,256.0,60.0,M1 7 Çekirdekli,13.0,22.9733
2,16,1,AMD Ryzen 7,5.0,1920 x 1080,512.0,16.0,0.0,60.0,AMD Radeon Graphics,15.6,13.0990
3,2,1,Intel Core i5,11.0,1920 x 1080,512.0,8.0,0.0,144.0,Nvidia GeForce RTX 2050,15.6,24.7500
4,0,2,Intel Celeron,2.0,1920 x 1080,128.0,4.0,0.0,60.0,Intel UHD Graphics,15.6,6.2900

In [44]:
df['Islemci_Tipi'].value_counts()

Intel Core i5              763
Intel Core i7              278
AMD Ryzen 5                116
AMD Ryzen 7                116
Intel Core i3              114
Intel Celeron               76
Apple M1                    67
Intel Core i9               58
AMD Ryzen 3                 42
M2                          22
Apple M2                    13
Intel Xeon                  11
MediaTek P60T               10
AMD Ryzen 9                  8
AMD                          7
AMD Athlon                   6
Apple M1 Pro                 5
Intel Pentium                5
Intel Core M                 4
M3                           4
Intel Atom                   3
Apple M2 Pro                 2
AMD E                        2
AMD A6                       2
AMD A4                       2
Ryzen Z1                     1
AMD A9                       1
Ryzen Z1 Extreme             1
Apple M1 Max                 1
Apple M2 Max                 1
Intel Xeon W Serisi          1
Intel Pentium Dual Core      1
Name: Islemci_Tipi, dtype: int64

In [45]:
df['Islemci_Tipi'] = enc.fit_transform(df['Islemci_Tipi'])

In [46]:
df['Islemci_Tipi'].value_counts()

20    763
21    278
7     116
8     116
19    114
17     76
10     67
22     58
6      42
32     33
27     22
13     13
25     11
29     10
9       8
0       7
4       6
12      5
23      5
28      4
18      4
16      3
15      2
5       2
2       2
1       2
30      1
3       1
31      1
11      1
14      1
26      1
24      1
Name: Islemci_Tipi, dtype: int64

In [47]:
df = df.drop(['Cozunurluk'],axis=1)

In [49]:
df['Ekran_Karti'].value_counts()

Intel Iris Graphics       259
Nvidia GeForce MX330      201
Dahili Ekran Kartı        163
Intel UHD Graphics        161
AMD Radeon Graphics       146
                         ...
AMD Radeon R5 M530          1
Nvidia RTX A4000            1
AMD Radeon R7               1
Nvidia Quadro P2200         1
Nvidia Quadro RTX 3000      1
Name: Ekran_Karti, Length: 70, dtype: int64

In [50]:
df['Ekran_Karti'] = enc.fit_transform(df['Ekran_Karti'])

In [51]:
df['Ekran_Karti'].value_counts()

21    259
40    201
14    163
24    161
3     146
     ...
8       1
64      1
9       1
18      1
61      1
Name: Ekran_Karti, Length: 71, dtype: int64

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1776 entries, 0 to 1775
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Ekran_Boyutu          1751 non-null   float64
 1   Ekran_Karti           1743 non-null   object
 2   Ekran_Yenileme_Hizi   1727 non-null   float64
 3   Hard_Disk_Kapasitesi  1736 non-null   float64
 4   Ram                   1743 non-null   float64
 5   SSD_Kapasitesi        1751 non-null   float64
 6   Cozunurluk            1743 non-null   object
 7   Islemci_Nesli         1736 non-null   float64
 8   Islemci_Tipi          1743 non-null   object
 9   Isletim_Sistemi       1743 non-null   object
 10  url                   1776 non-null   object
 11  price                 1776 non-null   float64
 12  marka                 1776 non-null   object
dtypes: float64(7), object(6)
memory usage: 180.5+ KB

In [ ]:
# colunlarda boş yerler var

In [54]:
df.head(10)

,marka,Isletim_Sistemi,Islemci_Tipi,Islemci_Nesli,SSD_Kapasitesi,Ram,Hard_Disk_Kapasitesi,Ekran_Yenileme_Hizi,Ekran_Karti,Ekran_Boyutu,Fiyat
0,16,1,17,4.0,0.0,4.0,0.0,60.0,14,15.6,6.7990
1,18,3,10,13.0,256.0,16.0,256.0,60.0,28,13.0,22.9733
2,16,1,8,5.0,512.0,16.0,0.0,60.0,3,15.6,13.0990
3,2,1,20,11.0,512.0,8.0,0.0,144.0,44,15.6,24.7500
4,0,2,17,2.0,128.0,4.0,0.0,60.0,24,15.6,6.2900
5,0,1,6,7.0,256.0,8.0,0.0,60.0,3,15.6,8.9990
6,16,1,4,7.0,256.0,8.0,0.0,60.0,3,15.6,8.1990
7,19,5,21,12.0,512.0,16.0,0.0,144.0,45,15.6,31.6799
8,13,5,20,11.0,256.0,8.0,256.0,60.0,21,15.6,14.3800
9,3,5,17,13.0,120.0,4.0,0.0,60.0,25,15.6,6.9390

In [55]:
df.Ekran_Boyutu.fillna(15.6,inplace=True)
df.Ekran_Karti.fillna(21,inplace=True)
df.Ekran_Yenileme_Hizi.fillna(60.0,inplace=True)
df.Hard_Disk_Kapasitesi.fillna(0.0,inplace=True)
df.Ram.fillna(16.0,inplace=True)
df.SSD_Kapasitesi.fillna(256.0,inplace=True)
df.Islemci_Nesli.fillna(10.0,inplace=True)
df.Islemci_Tipi.fillna(20,inplace=True)
df.Isletim_Sistemi.fillna(1,inplace=True)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1776 entries, 0 to 1775
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   marka                 1776 non-null   int32
 1   Isletim_Sistemi       1776 non-null   int32
 2   Islemci_Tipi          1776 non-null   int32
 3   Islemci_Nesli         1776 non-null   float64
 4   SSD_Kapasitesi        1776 non-null   float64
 5   Ram                   1776 non-null   float64
 6   Hard_Disk_Kapasitesi  1776 non-null   float64
 7   Ekran_Yenileme_Hizi   1776 non-null   float64
 8   Ekran_Karti           1776 non-null   int32
 9   Ekran_Boyutu          1776 non-null   float64
 10  Fiyat                 1776 non-null   float64
dtypes: float64(7), int32(4)
memory usage: 125.0 KB

In [57]:
df.to_csv("laptop-fill-training.csv",index=False)